name: Trigger auto deployment for ss-api
on:
  push:
    branches: 
      [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Log in to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.SSAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.SSAPI_REGISTRY_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: kaaw/ss-api:latest
