name: Trigger auto deployment for ss-api
on:  
  push:
    branches: 
      [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Log in to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.SSAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.SSAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: kaaw/ss-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SSAPI_AZURE_CREDENTIALS }}
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          containerAppName: ss-api
          resourceGroup: DefaultResourceGroup-CUS
          imageToDeploy: kaaw/ss-api:latest
